/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Octaviano
 */
public class ViewMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenu
     */
    public ViewMenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_CiaLogo = new javax.swing.JLabel();
        jmi_detalle_compra1 = new javax.swing.JMenuBar();
        jm_catalogos = new javax.swing.JMenu();
        jmi_proveedores = new javax.swing.JMenuItem();
        jmi_clientes = new javax.swing.JMenuItem();
        jmi_empleados_compras = new javax.swing.JMenuItem();
        jmi_empleados_ventas = new javax.swing.JMenuItem();
        jmi_sucursales = new javax.swing.JMenuItem();
        jmi_productos = new javax.swing.JMenuItem();
        jm_detalles = new javax.swing.JMenu();
        jmi_detallecompra = new javax.swing.JMenuItem();
        jmi_detalleventa = new javax.swing.JMenuItem();
        jm_nueva_sucursal = new javax.swing.JMenu();
        jmi_agregar_Sucursal = new javax.swing.JMenuItem();
        jmi_descuentos = new javax.swing.JMenuItem();
        jmi_promociones = new javax.swing.JMenuItem();
        jm_opciones = new javax.swing.JMenu();
        jmi_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jl_CiaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CIA-Developers.png"))); // NOI18N

        jmi_detalle_compra1.setBackground(new java.awt.Color(102, 102, 102));
        jmi_detalle_compra1.setPreferredSize(new java.awt.Dimension(88, 35));

        jm_catalogos.setBackground(new java.awt.Color(255, 255, 102));
        jm_catalogos.setForeground(new java.awt.Color(255, 255, 255));
        jm_catalogos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/catalogos.png"))); // NOI18N
        jm_catalogos.setText("Catalogos");

        jmi_proveedores.setBackground(new java.awt.Color(255, 255, 255));
        jmi_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/Proveedores.png"))); // NOI18N
        jmi_proveedores.setText("Proveedores");
        jm_catalogos.add(jmi_proveedores);

        jmi_clientes.setBackground(new java.awt.Color(255, 255, 255));
        jmi_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/clientes.png"))); // NOI18N
        jmi_clientes.setText("Clientes");
        jm_catalogos.add(jmi_clientes);

        jmi_empleados_compras.setBackground(new java.awt.Color(255, 255, 255));
        jmi_empleados_compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/Empleados.png"))); // NOI18N
        jmi_empleados_compras.setText("Empleados compras");
        jm_catalogos.add(jmi_empleados_compras);

        jmi_empleados_ventas.setBackground(new java.awt.Color(255, 255, 255));
        jmi_empleados_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/Empleados.png"))); // NOI18N
        jmi_empleados_ventas.setText("Empleados ventas");
        jm_catalogos.add(jmi_empleados_ventas);

        jmi_sucursales.setBackground(new java.awt.Color(255, 255, 255));
        jmi_sucursales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/sucursales.png"))); // NOI18N
        jmi_sucursales.setText("sucursales");
        jm_catalogos.add(jmi_sucursales);

        jmi_productos.setBackground(new java.awt.Color(255, 255, 255));
        jmi_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/productos.png"))); // NOI18N
        jmi_productos.setText("Productos");
        jm_catalogos.add(jmi_productos);

        jmi_detalle_compra1.add(jm_catalogos);

        jm_detalles.setBackground(new java.awt.Color(0, 153, 204));
        jm_detalles.setForeground(new java.awt.Color(255, 255, 255));
        jm_detalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aceptar.png"))); // NOI18N
        jm_detalles.setText("Detalles ");

        jmi_detallecompra.setBackground(new java.awt.Color(255, 255, 255));
        jmi_detallecompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/compras.png"))); // NOI18N
        jmi_detallecompra.setText("Detalle Compra");
        jm_detalles.add(jmi_detallecompra);

        jmi_detalleventa.setBackground(new java.awt.Color(255, 255, 255));
        jmi_detalleventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/Ventas.png"))); // NOI18N
        jmi_detalleventa.setText("Detalle Venta");
        jmi_detalleventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_detalleventaActionPerformed(evt);
            }
        });
        jm_detalles.add(jmi_detalleventa);

        jmi_detalle_compra1.add(jm_detalles);

        jm_nueva_sucursal.setForeground(new java.awt.Color(255, 255, 255));
        jm_nueva_sucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/accionesAdmin.png"))); // NOI18N
        jm_nueva_sucursal.setText("Acciones");

        jmi_agregar_Sucursal.setBackground(new java.awt.Color(255, 255, 255));
        jmi_agregar_Sucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar.png"))); // NOI18N
        jmi_agregar_Sucursal.setText("Agregar Nueva Sucursal ");
        jm_nueva_sucursal.add(jmi_agregar_Sucursal);

        jmi_descuentos.setBackground(new java.awt.Color(255, 255, 255));
        jmi_descuentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/descuentos.png"))); // NOI18N
        jmi_descuentos.setText("Descuentos");
        jm_nueva_sucursal.add(jmi_descuentos);

        jmi_promociones.setBackground(new java.awt.Color(255, 255, 255));
        jmi_promociones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/promociones.png"))); // NOI18N
        jmi_promociones.setText("Promociones");
        jm_nueva_sucursal.add(jmi_promociones);

        jmi_detalle_compra1.add(jm_nueva_sucursal);

        jm_opciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/opciones.png"))); // NOI18N
        jm_opciones.setText("Opciones");

        jmi_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu/Salir.png"))); // NOI18N
        jmi_salir.setText("Salir");
        jm_opciones.add(jmi_salir);

        jmi_detalle_compra1.add(jm_opciones);

        setJMenuBar(jmi_detalle_compra1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(881, Short.MAX_VALUE)
                .addComponent(jl_CiaLogo)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(423, Short.MAX_VALUE)
                .addComponent(jl_CiaLogo)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_detalleventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_detalleventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_detalleventaActionPerformed

    private void jmi_descuentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_descuentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_descuentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_CiaLogo;
    public javax.swing.JMenu jm_catalogos;
    public javax.swing.JMenu jm_detalles;
    public javax.swing.JMenu jm_nueva_sucursal;
    private javax.swing.JMenu jm_opciones;
    public javax.swing.JMenuItem jmi_agregar_Sucursal;
    public javax.swing.JMenuItem jmi_clientes;
    public javax.swing.JMenuItem jmi_descuentos;
    public javax.swing.JMenuBar jmi_detalle_compra1;
    public javax.swing.JMenuItem jmi_detallecompra;
    public javax.swing.JMenuItem jmi_detalleventa;
    public javax.swing.JMenuItem jmi_empleados_compras;
    public javax.swing.JMenuItem jmi_empleados_ventas;
    public javax.swing.JMenuItem jmi_productos;
    public javax.swing.JMenuItem jmi_promociones;
    public javax.swing.JMenuItem jmi_proveedores;
    private javax.swing.JMenuItem jmi_salir;
    public javax.swing.JMenuItem jmi_sucursales;
    // End of variables declaration//GEN-END:variables
}

