/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Octaviano
 */
public class ViewVENTAS extends javax.swing.JPanel {

    /**
     * Creates new form ViewVENTAS
     */
    public ViewVENTAS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_titulo2 = new javax.swing.JPanel();
        jl_titulo2 = new javax.swing.JLabel();
        fecha = new rojeru_san.RSLabelFecha();
        hora = new rojeru_san.RSLabelHora();
        jp_datos = new javax.swing.JPanel();
        jl_empleado = new javax.swing.JLabel();
        jl_numero_compras = new javax.swing.JLabel();
        jl_cantidad = new javax.swing.JLabel();
        jtf_cantidad = new javax.swing.JTextField();
        jl_no_sucursal = new javax.swing.JLabel();
        jl_precio_compra = new javax.swing.JLabel();
        jtf_precio = new javax.swing.JTextField();
        jp_cliente = new javax.swing.JPanel();
        jl_numero_proveedor = new javax.swing.JLabel();
        jcb_rfc_cliente = new javax.swing.JComboBox<>();
        jl_nombre_proveedor = new javax.swing.JLabel();
        jtf_nombre_cliente = new javax.swing.JTextField();
        jl_telefono_proveedor = new javax.swing.JLabel();
        jtf_puntos_acumulados = new javax.swing.JTextField();
        jtf_numero_venta = new javax.swing.JTextField();
        jl_total = new javax.swing.JLabel();
        jtf_total = new javax.swing.JTextField();
        jp_productos = new javax.swing.JPanel();
        jl_codigo_producto = new javax.swing.JLabel();
        jl_nombre_producto = new javax.swing.JLabel();
        jtf_nombre_producto = new javax.swing.JTextField();
        jl_tipo_producto = new javax.swing.JLabel();
        jtf_tipo_producto = new javax.swing.JTextField();
        jl_marca_producto = new javax.swing.JLabel();
        jtf_marca_producto = new javax.swing.JTextField();
        jcb_codigo_producto = new javax.swing.JComboBox<>();
        jcb_numero_sucursal = new javax.swing.JComboBox<>();
        jcb_rfc = new javax.swing.JComboBox<>();
        jl_nombre_empleado = new javax.swing.JLabel();
        jtf_nombre_empleado = new javax.swing.JTextField();
        jl_status = new javax.swing.JLabel();
        jl_status_producto = new javax.swing.JLabel();
        jb_agregar = new javax.swing.JButton();
        jb_nuevo = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jb_modificar = new javax.swing.JButton();
        jl_agregar = new javax.swing.JLabel();
        jl_modificar = new javax.swing.JLabel();
        jl_nuevo = new javax.swing.JLabel();
        jl_eliminar = new javax.swing.JLabel();
        jp_table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_vista = new javax.swing.JTable();
        jtf_subtotal = new javax.swing.JTextField();
        jl_subtotal = new javax.swing.JLabel();
        jl_iva = new javax.swing.JLabel();
        jtf_iva = new javax.swing.JTextField();
        jl_importe = new javax.swing.JLabel();
        jtf_importe = new javax.swing.JTextField();
        jb_realizar_venta = new javax.swing.JButton();
        jp_pago = new javax.swing.JPanel();
        jl_efectivo = new javax.swing.JLabel();
        jtf_efectivo = new javax.swing.JTextField();
        jl_cambio = new javax.swing.JLabel();
        jtf_cambio = new javax.swing.JTextField();
        jl_aplicar_descuentos = new javax.swing.JLabel();
        jb_aplicar_descuento = new javax.swing.JButton();
        jl_codigo_descuento = new javax.swing.JLabel();
        jcb_codigo_descuento = new javax.swing.JComboBox<>();
        jtf_puntos_requeridos = new javax.swing.JTextField();
        jl_puntos_requeridos = new javax.swing.JLabel();
        jl_porcentaje = new javax.swing.JLabel();
        jtf_porcentaje = new javax.swing.JTextField();
        jl_descuento = new javax.swing.JLabel();
        jtf_descuento = new javax.swing.JTextField();
        jl_puntos_ganados = new javax.swing.JLabel();
        jtf_puntos_ganados = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1150, 692));
        setMinimumSize(new java.awt.Dimension(1150, 692));

        jp_titulo2.setBackground(new java.awt.Color(153, 204, 255));
        jp_titulo2.setMaximumSize(new java.awt.Dimension(1150, 692));
        jp_titulo2.setMinimumSize(new java.awt.Dimension(1150, 692));
        jp_titulo2.setPreferredSize(new java.awt.Dimension(1150, 692));

        jl_titulo2.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
        jl_titulo2.setForeground(new java.awt.Color(102, 102, 102));
        jl_titulo2.setText("Ventas");

        fecha.setForeground(new java.awt.Color(0, 0, 153));
        fecha.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        fecha.setFormato("dd-MM-yyyy");

        hora.setForeground(new java.awt.Color(0, 0, 153));
        hora.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        javax.swing.GroupLayout jp_titulo2Layout = new javax.swing.GroupLayout(jp_titulo2);
        jp_titulo2.setLayout(jp_titulo2Layout);
        jp_titulo2Layout.setHorizontalGroup(
            jp_titulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_titulo2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jl_titulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jp_titulo2Layout.setVerticalGroup(
            jp_titulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_titulo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_titulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_datos.setBackground(new java.awt.Color(255, 255, 255));
        jp_datos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 153, 255))); // NOI18N

        jl_empleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_empleado.setText("Empleado:");

        jl_numero_compras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_numero_compras.setText("No. venta:");

        jl_cantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_cantidad.setText("Cantiad venta:");

        jtf_cantidad.setBackground(new java.awt.Color(153, 153, 153));
        jtf_cantidad.setText("0");

        jl_no_sucursal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_no_sucursal.setText("No_ sucursal:");

        jl_precio_compra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_precio_compra.setText("Precio venta $:");

        jtf_precio.setEditable(false);
        jtf_precio.setBackground(new java.awt.Color(153, 153, 153));
        jtf_precio.setText("0.0");

        jp_cliente.setBackground(new java.awt.Color(255, 255, 255));
        jp_cliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 153, 255))); // NOI18N
        jp_cliente.setForeground(new java.awt.Color(51, 153, 255));

        jl_numero_proveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_numero_proveedor.setText("RFC:");

        jcb_rfc_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jl_nombre_proveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_nombre_proveedor.setText("Nombre :");

        jtf_nombre_cliente.setEditable(false);

        jl_telefono_proveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_telefono_proveedor.setText("Puntos acumulados");

        jtf_puntos_acumulados.setEditable(false);

        javax.swing.GroupLayout jp_clienteLayout = new javax.swing.GroupLayout(jp_cliente);
        jp_cliente.setLayout(jp_clienteLayout);
        jp_clienteLayout.setHorizontalGroup(
            jp_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_clienteLayout.createSequentialGroup()
                .addGroup(jp_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_clienteLayout.createSequentialGroup()
                        .addComponent(jl_numero_proveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_rfc_cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp_clienteLayout.createSequentialGroup()
                        .addComponent(jl_nombre_proveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_nombre_cliente)))
                .addGap(10, 10, 10))
            .addGroup(jp_clienteLayout.createSequentialGroup()
                .addComponent(jl_telefono_proveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_puntos_acumulados, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );
        jp_clienteLayout.setVerticalGroup(
            jp_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_rfc_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_numero_proveedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre_proveedor)
                    .addComponent(jtf_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_telefono_proveedor)
                    .addComponent(jtf_puntos_acumulados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtf_numero_venta.setEditable(false);

        jl_total.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_total.setText("Total   $:");

        jtf_total.setEditable(false);
        jtf_total.setBackground(new java.awt.Color(0, 0, 0));
        jtf_total.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtf_total.setForeground(new java.awt.Color(51, 153, 255));
        jtf_total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_total.setText("0.00");
        jtf_total.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jp_productos.setBackground(new java.awt.Color(255, 255, 255));
        jp_productos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 153, 255))); // NOI18N
        jp_productos.setForeground(new java.awt.Color(51, 153, 255));

        jl_codigo_producto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_codigo_producto.setText("Codigo producto:");

        jl_nombre_producto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_nombre_producto.setText("Nombre producto:");

        jtf_nombre_producto.setEditable(false);

        jl_tipo_producto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_tipo_producto.setText("Tipo producto:");

        jtf_tipo_producto.setEditable(false);

        jl_marca_producto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_marca_producto.setText(" Marca producto:");

        jtf_marca_producto.setEditable(false);

        jcb_codigo_producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        javax.swing.GroupLayout jp_productosLayout = new javax.swing.GroupLayout(jp_productos);
        jp_productos.setLayout(jp_productosLayout);
        jp_productosLayout.setHorizontalGroup(
            jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_productosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jl_marca_producto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_marca_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jp_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_codigo_producto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_codigo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jp_productosLayout.createSequentialGroup()
                .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_nombre_producto)
                    .addComponent(jl_tipo_producto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_nombre_producto)
                    .addComponent(jtf_tipo_producto))
                .addContainerGap())
        );
        jp_productosLayout.setVerticalGroup(
            jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_codigo_producto)
                    .addComponent(jcb_codigo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre_producto)
                    .addComponent(jtf_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_tipo_producto)
                    .addComponent(jtf_tipo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_marca_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_marca_producto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jcb_numero_sucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jcb_rfc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jl_nombre_empleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_nombre_empleado.setText("Nombre:");

        jtf_nombre_empleado.setEditable(false);

        jl_status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_status.setText("Status:");

        jl_status_producto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_status_producto.setForeground(new java.awt.Color(204, 0, 0));
        jl_status_producto.setText("Normal");

        javax.swing.GroupLayout jp_datosLayout = new javax.swing.GroupLayout(jp_datos);
        jp_datos.setLayout(jp_datosLayout);
        jp_datosLayout.setHorizontalGroup(
            jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_datosLayout.createSequentialGroup()
                        .addComponent(jl_empleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jl_numero_compras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_numero_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jl_no_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_numero_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jl_status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_status_producto))
                    .addGroup(jp_datosLayout.createSequentialGroup()
                        .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jp_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp_datosLayout.createSequentialGroup()
                                .addComponent(jl_nombre_empleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_nombre_empleado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jp_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_datosLayout.createSequentialGroup()
                                .addComponent(jl_precio_compra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_datosLayout.createSequentialGroup()
                                .addComponent(jl_total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_total, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_datosLayout.createSequentialGroup()
                                .addComponent(jl_cantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jp_datosLayout.setVerticalGroup(
            jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datosLayout.createSequentialGroup()
                .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jl_status)
                        .addComponent(jl_status_producto))
                    .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jl_empleado)
                        .addComponent(jl_numero_compras)
                        .addComponent(jtf_numero_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jl_no_sucursal)
                        .addComponent(jcb_numero_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcb_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_datosLayout.createSequentialGroup()
                        .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_nombre_empleado)
                            .addComponent(jtf_nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jp_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(jp_datosLayout.createSequentialGroup()
                        .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jp_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp_datosLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_cantidad)
                                    .addComponent(jtf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_precio_compra)
                                    .addComponent(jtf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_total)
                                    .addComponent(jtf_total, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jb_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BotonAgregar.png"))); // NOI18N

        jb_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nuevo.png"))); // NOI18N

        jb_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png"))); // NOI18N

        jb_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ModProd.jpeg"))); // NOI18N

        jl_agregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_agregar.setText("Agregar");

        jl_modificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_modificar.setText("Modificar");

        jl_nuevo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_nuevo.setText("Nuevo");

        jl_eliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_eliminar.setForeground(new java.awt.Color(51, 51, 51));
        jl_eliminar.setText("Eliminar");

        jp_table.setBackground(new java.awt.Color(255, 255, 51));

        jt_vista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Compra", "Codigo Producto", "Nombre Producto", "Precio", "Cantidad", "Total"
            }
        ));
        jScrollPane1.setViewportView(jt_vista);

        javax.swing.GroupLayout jp_tableLayout = new javax.swing.GroupLayout(jp_table);
        jp_table.setLayout(jp_tableLayout);
        jp_tableLayout.setHorizontalGroup(
            jp_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jp_tableLayout.setVerticalGroup(
            jp_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtf_subtotal.setEditable(false);
        jtf_subtotal.setBackground(new java.awt.Color(153, 153, 153));
        jtf_subtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_subtotal.setText("0.0");

        jl_subtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_subtotal.setText("Subtotal  $:");

        jl_iva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_iva.setText("IVA  $:");

        jtf_iva.setEditable(false);
        jtf_iva.setBackground(new java.awt.Color(153, 153, 153));
        jtf_iva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_iva.setText("0.0");

        jl_importe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jl_importe.setForeground(new java.awt.Color(0, 102, 204));
        jl_importe.setText("IMPORTE   $:");

        jtf_importe.setEditable(false);
        jtf_importe.setBackground(new java.awt.Color(0, 0, 0));
        jtf_importe.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtf_importe.setForeground(new java.awt.Color(255, 0, 0));
        jtf_importe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_importe.setText("0.00");
        jtf_importe.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jb_realizar_venta.setBackground(new java.awt.Color(51, 51, 51));
        jb_realizar_venta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jb_realizar_venta.setForeground(new java.awt.Color(255, 255, 255));
        jb_realizar_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Compra_venta.png"))); // NOI18N
        jb_realizar_venta.setText("Realizar Venta...");

        jp_pago.setBackground(new java.awt.Color(255, 255, 255));
        jp_pago.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 153, 255))); // NOI18N
        jp_pago.setForeground(new java.awt.Color(51, 153, 255));

        jl_efectivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_efectivo.setText("Efectivo:");

        jtf_efectivo.setBackground(new java.awt.Color(153, 153, 153));
        jtf_efectivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtf_efectivo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_efectivo.setText("0.0");

        jl_cambio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_cambio.setText("Cambio:");

        jtf_cambio.setEditable(false);
        jtf_cambio.setBackground(new java.awt.Color(153, 153, 153));
        jtf_cambio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtf_cambio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_cambio.setText("0.0");

        jl_aplicar_descuentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_aplicar_descuentos.setForeground(new java.awt.Color(153, 0, 153));
        jl_aplicar_descuentos.setText("Aplicar  descuento.");

        jb_aplicar_descuento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/descuento_ventas.png"))); // NOI18N

        jl_codigo_descuento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_codigo_descuento.setText("codigo descuento:");

        jcb_codigo_descuento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtf_puntos_requeridos.setEditable(false);
        jtf_puntos_requeridos.setBackground(new java.awt.Color(204, 102, 255));
        jtf_puntos_requeridos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_puntos_requeridos.setText("0.0");

        jl_puntos_requeridos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_puntos_requeridos.setText("puntos requeridos:");

        jl_porcentaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_porcentaje.setText("porcentaje:");

        jtf_porcentaje.setEditable(false);
        jtf_porcentaje.setBackground(new java.awt.Color(204, 102, 255));
        jtf_porcentaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_porcentaje.setText("0.0");

        jl_descuento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_descuento.setText("descuento $:");

        jtf_descuento.setEditable(false);
        jtf_descuento.setBackground(new java.awt.Color(204, 102, 255));
        jtf_descuento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_descuento.setText("0.0");

        javax.swing.GroupLayout jp_pagoLayout = new javax.swing.GroupLayout(jp_pago);
        jp_pago.setLayout(jp_pagoLayout);
        jp_pagoLayout.setHorizontalGroup(
            jp_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_pagoLayout.createSequentialGroup()
                .addGroup(jp_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_pagoLayout.createSequentialGroup()
                        .addGroup(jp_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jl_puntos_requeridos)
                                .addComponent(jl_porcentaje))
                            .addComponent(jb_aplicar_descuento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtf_porcentaje, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                .addComponent(jtf_puntos_requeridos))
                            .addComponent(jl_aplicar_descuentos)))
                    .addGroup(jp_pagoLayout.createSequentialGroup()
                        .addComponent(jl_codigo_descuento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_codigo_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jp_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jp_pagoLayout.createSequentialGroup()
                            .addComponent(jl_efectivo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtf_efectivo))
                        .addGroup(jp_pagoLayout.createSequentialGroup()
                            .addComponent(jl_cambio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtf_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_pagoLayout.createSequentialGroup()
                        .addComponent(jl_descuento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jp_pagoLayout.setVerticalGroup(
            jp_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_pagoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_aplicar_descuentos))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_pagoLayout.createSequentialGroup()
                .addGroup(jp_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_pagoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jp_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_codigo_descuento)
                            .addComponent(jcb_codigo_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_descuento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_puntos_requeridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_puntos_requeridos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_porcentaje))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp_pagoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jp_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_efectivo)
                            .addComponent(jtf_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)))
                .addGroup(jp_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jl_cambio)
                        .addComponent(jtf_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jb_aplicar_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jl_puntos_ganados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_puntos_ganados.setForeground(new java.awt.Color(0, 0, 153));
        jl_puntos_ganados.setText("puntos ganados:");

        jtf_puntos_ganados.setBackground(new java.awt.Color(153, 204, 255));
        jtf_puntos_ganados.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_puntos_ganados.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_titulo2, javax.swing.GroupLayout.DEFAULT_SIZE, 1165, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jp_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jl_subtotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jl_iva)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jb_realizar_venta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtf_importe, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jl_importe)))
                            .addComponent(jl_puntos_ganados, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_puntos_ganados, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jp_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jp_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_agregar)
                                    .addComponent(jb_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jb_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_nuevo))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_modificar)
                                    .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_eliminar)
                                    .addComponent(jb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 16, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb_agregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_agregar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb_modificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_modificar)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb_nuevo)
                                .addGap(7, 7, 7)
                                .addComponent(jl_nuevo))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(67, 67, 67)
                                    .addComponent(jl_eliminar)))))
                    .addComponent(jp_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jl_importe)
                                .addGap(8, 8, 8)
                                .addComponent(jtf_importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jl_puntos_ganados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_puntos_ganados, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtf_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_subtotal))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_iva)
                                    .addComponent(jtf_iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(jb_realizar_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSLabelFecha fecha;
    private rojeru_san.RSLabelHora hora;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_aplicar_descuento;
    public javax.swing.JButton jb_eliminar;
    public javax.swing.JButton jb_modificar;
    public javax.swing.JButton jb_nuevo;
    public javax.swing.JButton jb_realizar_venta;
    private javax.swing.JComboBox<String> jcb_codigo_descuento;
    public javax.swing.JComboBox<String> jcb_codigo_producto;
    public javax.swing.JComboBox<String> jcb_numero_sucursal;
    public javax.swing.JComboBox<String> jcb_rfc;
    public javax.swing.JComboBox<String> jcb_rfc_cliente;
    public javax.swing.JLabel jl_agregar;
    public javax.swing.JLabel jl_aplicar_descuentos;
    private javax.swing.JLabel jl_cambio;
    public javax.swing.JLabel jl_cantidad;
    public javax.swing.JLabel jl_codigo_descuento;
    public javax.swing.JLabel jl_codigo_producto;
    public javax.swing.JLabel jl_descuento;
    private javax.swing.JLabel jl_efectivo;
    public javax.swing.JLabel jl_eliminar;
    public javax.swing.JLabel jl_empleado;
    public javax.swing.JLabel jl_importe;
    public javax.swing.JLabel jl_iva;
    public javax.swing.JLabel jl_marca_producto;
    public javax.swing.JLabel jl_modificar;
    public javax.swing.JLabel jl_no_sucursal;
    public javax.swing.JLabel jl_nombre_empleado;
    public javax.swing.JLabel jl_nombre_producto;
    public javax.swing.JLabel jl_nombre_proveedor;
    public javax.swing.JLabel jl_nuevo;
    public javax.swing.JLabel jl_numero_compras;
    public javax.swing.JLabel jl_numero_proveedor;
    public javax.swing.JLabel jl_porcentaje;
    public javax.swing.JLabel jl_precio_compra;
    public javax.swing.JLabel jl_puntos_ganados;
    public javax.swing.JLabel jl_puntos_requeridos;
    public javax.swing.JLabel jl_status;
    public javax.swing.JLabel jl_status_producto;
    public javax.swing.JLabel jl_subtotal;
    public javax.swing.JLabel jl_telefono_proveedor;
    public javax.swing.JLabel jl_tipo_producto;
    public javax.swing.JLabel jl_titulo2;
    public javax.swing.JLabel jl_total;
    public javax.swing.JPanel jp_cliente;
    public javax.swing.JPanel jp_datos;
    public javax.swing.JPanel jp_pago;
    public javax.swing.JPanel jp_productos;
    public javax.swing.JPanel jp_table;
    private javax.swing.JPanel jp_titulo2;
    public javax.swing.JTable jt_vista;
    public javax.swing.JTextField jtf_cambio;
    public javax.swing.JTextField jtf_cantidad;
    public javax.swing.JTextField jtf_descuento;
    public javax.swing.JTextField jtf_efectivo;
    public javax.swing.JTextField jtf_importe;
    public javax.swing.JTextField jtf_iva;
    public javax.swing.JTextField jtf_marca_producto;
    public javax.swing.JTextField jtf_nombre_cliente;
    public javax.swing.JTextField jtf_nombre_empleado;
    public javax.swing.JTextField jtf_nombre_producto;
    public javax.swing.JTextField jtf_numero_venta;
    public javax.swing.JTextField jtf_porcentaje;
    public javax.swing.JTextField jtf_precio;
    public javax.swing.JTextField jtf_puntos_acumulados;
    public javax.swing.JTextField jtf_puntos_ganados;
    public javax.swing.JTextField jtf_puntos_requeridos;
    public javax.swing.JTextField jtf_subtotal;
    public javax.swing.JTextField jtf_tipo_producto;
    public javax.swing.JTextField jtf_total;
    // End of variables declaration//GEN-END:variables
}
