/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Octaviano
 */
public class ViewLogin extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public ViewLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.setOpacity(0.95f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_passwd = new javax.swing.JLabel();
        jcb_tipo_admin = new javax.swing.JComboBox<>();
        jl_tipo = new javax.swing.JLabel();
        jl_usuario = new javax.swing.JLabel();
        jpf_passwd = new javax.swing.JPasswordField();
        jtf_usuario = new javax.swing.JTextField();
        jb_aceptar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesion");
        setMaximumSize(new java.awt.Dimension(604, 503));
        setMinimumSize(new java.awt.Dimension(604, 503));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jl_passwd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jl_passwd.setText("Contraseña:");
        getContentPane().add(jl_passwd);
        jl_passwd.setBounds(240, 250, 100, 25);

        jcb_tipo_admin.setBackground(new java.awt.Color(204, 204, 204));
        jcb_tipo_admin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcb_tipo_admin.setForeground(new java.awt.Color(0, 153, 204));
        jcb_tipo_admin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado Ventas", "Empleado Compras" }));
        jcb_tipo_admin.setBorder(null);
        getContentPane().add(jcb_tipo_admin);
        jcb_tipo_admin.setBounds(340, 110, 190, 30);

        jl_tipo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jl_tipo.setText("TIPO:");
        getContentPane().add(jl_tipo);
        jl_tipo.setBounds(280, 110, 40, 25);

        jl_usuario.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jl_usuario.setText("Usuario:");
        getContentPane().add(jl_usuario);
        jl_usuario.setBounds(270, 180, 60, 25);

        jpf_passwd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpf_passwd.setText("jPasswordField1");
        jpf_passwd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 102, 255), null, null));
        getContentPane().add(jpf_passwd);
        jpf_passwd.setBounds(340, 250, 190, 30);

        jtf_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 102, 255), null, null));
        getContentPane().add(jtf_usuario);
        jtf_usuario.setBounds(340, 180, 190, 30);

        jb_aceptar.setBackground(new java.awt.Color(51, 153, 255));
        jb_aceptar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jb_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        jb_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aceptar.png"))); // NOI18N
        jb_aceptar.setText("Aceptar");
        jb_aceptar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 153))); // NOI18N
        getContentPane().add(jb_aceptar);
        jb_aceptar.setBounds(90, 380, 120, 50);

        jb_cancelar.setBackground(new java.awt.Color(51, 153, 255));
        jb_cancelar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jb_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cerrar.png"))); // NOI18N
        jb_cancelar.setText("cancelar");
        jb_cancelar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 153))); // NOI18N
        getContentPane().add(jb_cancelar);
        jb_cancelar.setBounds(290, 380, 130, 50);

        jl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        getContentPane().add(jl_fondo);
        jl_fondo.setBounds(0, 1, 600, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jb_aceptar;
    public javax.swing.JButton jb_cancelar;
    public javax.swing.JComboBox<String> jcb_tipo_admin;
    public javax.swing.JLabel jl_fondo;
    public javax.swing.JLabel jl_passwd;
    public javax.swing.JLabel jl_tipo;
    public javax.swing.JLabel jl_usuario;
    public javax.swing.JPasswordField jpf_passwd;
    public javax.swing.JTextField jtf_usuario;
    // End of variables declaration//GEN-END:variables
}
